import { addDaysIso } from './dateHelpers';

export const mockOrderMasterRows = [
  {
    id: 'mock-order-1',
    order_code: 'JT-260503-01',
    customer: 'Jade Export',
    po_number: 'PO-8831',
    style_code: 'JTX-2401',
    style_reference: 'Performance polo / SMV 8.6',
    color: 'Navy',
    order_quantity: 2400,
    delivery_date: addDaysIso(6),
    shipment_date: addDaysIso(8),
    priority: 'high',
    current_stage: 'pre_stock',
    risk_level: 'amber',
    status: 'released',
  },
  {
    id: 'mock-order-2',
    order_code: 'JT-260503-02',
    customer: 'North Retail',
    po_number: 'PO-9014',
    style_code: 'NR-5510',
    style_reference: 'Fleece jogger / SMV 12.4',
    color: 'Charcoal',
    order_quantity: 1800,
    delivery_date: addDaysIso(3),
    shipment_date: addDaysIso(5),
    priority: 'urgent',
    current_stage: 'pre_stock',
    risk_level: 'red',
    status: 'active',
  },
  {
    id: 'mock-order-3',
    order_code: 'JT-260503-03',
    customer: 'Atlas Stores',
    po_number: 'PO-7742',
    style_code: 'AS-2040',
    style_reference: 'Woven shirt / SMV 10.2',
    color: 'White',
    order_quantity: 3200,
    delivery_date: addDaysIso(12),
    shipment_date: addDaysIso(14),
    priority: 'normal',
    current_stage: 'planning',
    risk_level: 'green',
    status: 'running',
  },
  {
    id: 'mock-order-4',
    order_code: 'JT-260503-04',
    customer: 'Marmara Basics',
    po_number: 'PO-1187',
    style_code: 'MB-4409',
    style_reference: 'Basic tee / SMV 6.8',
    color: 'Black',
    order_quantity: 5100,
    delivery_date: addDaysIso(1),
    shipment_date: addDaysIso(2),
    priority: 'urgent',
    current_stage: 'order_master',
    risk_level: 'high',
    status: 'released',
  },
];

export const mockMaterialReadinessRows = [
  {
    id: 'mock-material-1',
    order_id: 'mock-order-1',
    order_code: 'JT-260503-01',
    customer: 'Jade Export',
    style_code: 'JTX-2401',
    po_number: 'PO-8831',
    shipment_date: addDaysIso(8),
    current_stage: 'pre_stock',
    material_type: 'Main fabric',
    required_qty: 2450,
    received_qty: 2400,
    balance_qty: 50,
    readiness_percent: 98,
    expected_inhouse_date: addDaysIso(1),
    inspection_status: 'passed',
    approval_status: 'approved_partial',
    shortage_risk: 'amber',
  },
  {
    id: 'mock-material-2',
    order_id: 'mock-order-2',
    order_code: 'JT-260503-02',
    customer: 'North Retail',
    style_code: 'NR-5510',
    po_number: 'PO-9014',
    shipment_date: addDaysIso(5),
    current_stage: 'pre_stock',
    material_type: 'Rib and trims',
    required_qty: 1800,
    received_qty: 1410,
    balance_qty: 390,
    readiness_percent: 78,
    expected_inhouse_date: addDaysIso(2),
    inspection_status: 'pending',
    approval_status: 'waiting',
    shortage_risk: 'red',
  },
  {
    id: 'mock-material-3',
    order_id: 'mock-order-3',
    order_code: 'JT-260503-03',
    customer: 'Atlas Stores',
    style_code: 'AS-2040',
    po_number: 'PO-7742',
    shipment_date: addDaysIso(14),
    current_stage: 'planning',
    material_type: 'Packaging',
    required_qty: 3200,
    received_qty: 3200,
    balance_qty: 0,
    readiness_percent: 100,
    expected_inhouse_date: addDaysIso(-1),
    inspection_status: 'passed',
    approval_status: 'approved',
    shortage_risk: 'green',
  },
  {
    id: 'mock-material-4',
    order_id: 'mock-order-4',
    order_code: 'JT-260503-04',
    customer: 'Marmara Basics',
    style_code: 'MB-4409',
    po_number: 'PO-1187',
    shipment_date: addDaysIso(2),
    current_stage: 'order_master',
    material_type: 'Main fabric',
    required_qty: 5100,
    received_qty: 4520,
    balance_qty: 580,
    readiness_percent: 88.6,
    expected_inhouse_date: addDaysIso(1),
    inspection_status: 'recheck',
    approval_status: 'blocked',
    shortage_risk: 'red',
  },
];
